apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-api-svc
  name: todo-api-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: api-port
      name: todo-api-port
  selector:
    app: todo-api