apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: todo-api-clojure
build:
  artifacts:
    - image: todo-api-clojure
      context: ../api
      docker:
        dockerfile: ./app/Dockerfile
  local:
    push: false
    useBuildkit: true
manifests:
  helm:
    releases:
      - name: todo-api
        chartPath: app/helm
        setValues:
          replicas: 1
          imagePullPolicy: Never
