apiVersion: v1
kind: Service
metadata:
  labels:
    app: "todo-db-svc"
  name: "todo-db-svc"
spec:
  selector:
    app: todo-db
  type: NodePort
  ports:
  - name: "todo-db-port"
    port: 5432
    targetPort: db-port